name = "0x5eal/unzip"
version = "0.1.3"
description = "Unzip implementation in pure Luau"
license = "MIT"
authors = ["Erica Marigold <hi@devcomp.xyz>"]
repository = "https://github.com/0x5eal/luau-unzip"
private = false
includes = ["README.md", "LICENSE.md", "pesde.toml", "lib/**/*.luau", "!tests/**/*", "docs/**/*.md"]

[target]
environment = "luau"
lib = "lib/init.luau"

[engines]
pesde = "=0.6.0"
lune = "=0.8.9"

[dev_dependencies.asciitable]
name = "kimpure/asciitable"
version = "^0.2.1"
index = "https://github.com/pesde-pkg/index"

[dev_dependencies.frktest]
name = "itsfrank/frktest"
version = "^0.0.2"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.luau-lsp]
name = "pesde/luau_lsp"
version = "=1.39.2"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dev_dependencies.stylua]
name = "pesde/stylua"
version = "=2.0.2"
index = "https://github.com/pesde-pkg/index"
target = "lune"
